-- Documents (does not itself re-provision) the pg_cron jobs that drive the
-- Austin broker crawl. Same convention as zoho-projects-poll: the vault
-- secret + cron.schedule() calls were run once via
-- `supabase db query --linked -f <scratch file>` (not committed -- it held the
-- raw secret) so the secret never lands in git history.
--
-- These REPLACE the GitHub Actions workflow. Actions could not be used: the
-- repo's deploy token lacks the 'workflow' scope, so no workflow file can be
-- pushed. Running the crawl from Supabase also means no service key has to be
-- stored in GitHub -- the edge function gets one injected automatically.
--
-- Live jobs, all calling functions/v1/crawl-listings with an
-- 'x-cron-secret' header read live from vault (name 'crawl_cron_secret'),
-- ONE BROKER PER INVOCATION because a single source can page up to 25 times:
--
--   crawl-ecr      '1  5 * * 2,4,6'
--   crawl-aquila   '6  5 * * 2,4,6'
--   crawl-hpi      '11 5 * * 2,4,6'
--   crawl-cushman  '16 5 * * 2,4,6'
--   crawl-kucera   '21 5 * * 2,4,6'
--
-- 05:01 UTC Tue/Thu/Sat = 12:01 AM Austin. Staggered five minutes apart so the
-- sources never overlap. Slowest observed source is aquila at ~27s, well
-- inside the wall-clock limit.
--
-- DAYLIGHT SAVING CAVEAT: pg_cron 1.6.4 has no per-job timezone (cron.job has
-- no timezone column) and this database runs in UTC, so these are fixed UTC
-- times. They are correct while Austin is on CDT (UTC-5). When DST ends on
-- 2026-11-01 Austin moves to CST (UTC-6) and 05:01 UTC becomes 11:01 PM the
-- PREVIOUS evening -- i.e. Mon/Wed/Fri night rather than Tue/Thu/Sat morning.
-- Harmless for a crawl, but to keep the stated local time, change the hour
-- from 5 to 6 in each schedule after 2026-11-01 (and back to 5 in March).
--
-- To redo from scratch (e.g. secret rotation):
--   1. supabase secrets set CRAWL_CRON_SECRET=<new value>
--   2. via db query (scratch file, never committed):
--        delete from vault.secrets where name = 'crawl_cron_secret';
--        select vault.create_secret('<same value>', 'crawl_cron_secret', '...');
--      then unschedule/reschedule each crawl-<source> job.
